mvc/Models/ErrorViewModel.cs
using System;

namespace CoreUIStatic.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

mvc/Areas/Pages/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreUIStatic.Models;

namespace CoreUIStatic.Controllers
{
    [Area("Pages")]
    public class PagesController : Controller
    {

        public IActionResult Index()
        {
            return View("_404");
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult _404()
        {
            return View();
        }

        public IActionResult _500()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mvc/Controllers/CoreUIController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CoreUIStatic.Models;


namespace CoreUIStatic.Controllers
{

    public class CoreUIController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Widgets()
        {
            return View();
        }

        public IActionResult Charts()
        {
            return View();
        }


        public IActionResult Buttons(string id = "buttons")
        {
            string viewName = $"Buttons/{id}";
            return View(viewName);
        }

        public IActionResult Components(string id = "cards")
        {
            string viewName = $"Base/{id}";

            return View(viewName);
        }

        public IActionResult Icons(string id = "simple-line-icons")
        {
            string viewName = $"Icons/{id}";

            return View(viewName);
        }

        public IActionResult Notifications(string id = "alerts")
        {
            string viewName = $"Notifications/{id}";

            return View(viewName);
        }

        public IActionResult Pages(string id = "login")
        {
            string viewName = $"Pages/{id}";

            return View(viewName);
        }

        public IActionResult Theme(string id = "colors")
        {
            string viewName = $"Theme/{id}";
            return View(viewName);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreUIStatic.Models;

namespace CoreUIStatic.Controllers
{

    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mvc/Areas/Pages/Views/Shared/_Pages.cshtml
@{
    Layout = "";
}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="CoreUI Bootstrap 4 Admin Template">
    <meta name="author" content="Lukasz Holeczek">
    <meta name="keyword" content="CoreUI Bootstrap 4 Admin Template">
    <link rel="shortcut icon" href="~/img/favicon.png">

    <title>@ViewData["Name"]</title>

    <!-- Icons -->
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/node_modules/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" />

    <!-- Main styles for this application -->
    <link href="~/css/style.css" rel="stylesheet">

</head>

<body class="app flex-row align-items-center">
    @RenderBody()

    <!-- Bootstrap and necessary plugins -->
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

mvc/Views/CoreUI/Buttons/button-group.cshtml
@{
    ViewData["Name"] = "Button Group";
}
<div class="animated fadeIn">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <strong>Button group</strong>
                    <div class="card-actions">
                        <a href="http://coreui.io/docs/components/bootstrap-button-group/" target="_blank">
                            <small class="text-muted">docs</small>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-secondary">Left</button>
                        <button type="button" class="btn btn-secondary">Middle</button>
                        <button type="button" class="btn btn-secondary">Right</button>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Button group
                    <small>toolbar</small>
                </div>
                <div class="card-body">
                    <div class="btn-toolbar mb-3" role="toolbar" aria-label="Toolbar with button groups">
                        <div class="btn-group mr-2" role="group" aria-label="First group">
                            <button type="button" class="btn btn-secondary">1</button>
                            <button type="button" class="btn btn-secondary">2</button>
                            <button type="button" class="btn btn-secondary">3</button>
                            <button type="button" class="btn btn-secondary">4</button>
                        </div>
                        <div class="btn-group mr-2" role="group" aria-label="Second group">
                            <button type="button" class="btn btn-secondary">5</button>
                            <button type="button" class="btn btn-secondary">6</button>
                            <button type="button" class="btn btn-secondary">7</button>
                        </div>
                        <div class="btn-group" role="group" aria-label="Third group">
                            <button type="button" class="btn btn-secondary">8</button>
                        </div>
                    </div>

                    <div class="btn-toolbar mb-3" role="toolbar" aria-label="Toolbar with button groups">
                        <div class="btn-group mr-2" role="group" aria-label="First group">
                            <button type="button" class="btn btn-secondary">1</button>
                            <button type="button" class="btn btn-secondary">2</button>
                            <button type="button" class="btn btn-secondary">3</button>
                            <button type="button" class="btn btn-secondary">4</button>
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="btnGroupAddon">@@</span>
                            </div>
                            <input type="text" class="form-control" placeholder="Input group example" aria-label="Input group example" aria-describedby="btnGroupAddon">
                        </div>
                    </div>

                    <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
                        <div class="btn-group" role="group" aria-label="First group">
                            <button type="button" class="btn btn-secondary">1</button>
                            <button type="button" class="btn btn-secondary">2</button>
                            <button type="button" class="btn btn-secondary">3</button>
                            <button type="button" class="btn btn-secondary">4</button>
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="btnGroupAddon2">@@</span>
                            </div>
                            <input type="text" class="form-control" placeholder="Input group example" aria-label="Input group example" aria-describedby="btnGroupAddon2">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Button group
                    <small>sizing</small>
                </div>
                <div class="card-body">
                    <div class="btn-group btn-group-lg mb-3" role="group" aria-label="Large button group">
                        <button type="button" class="btn btn-secondary">Left</button>
                        <button type="button" class="btn btn-secondary">Middle</button>
                        <button type="button" class="btn btn-secondary">Right</button>
                    </div>
                    <br />
                    <div class="btn-group mb-3" role="group" aria-label="Default button group">
                        <button type="button" class="btn btn-secondary">Left</button>
                        <button type="button" class="btn btn-secondary">Middle</button>
                        <button type="button" class="btn btn-secondary">Right</button>
                    </div>
                    <br />
                    <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                        <button type="button" class="btn btn-secondary">Left</button>
                        <button type="button" class="btn btn-secondary">Middle</button>
                        <button type="button" class="btn btn-secondary">Right</button>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Button group
                    <small>nesting</small>
                </div>
                <div class="card-body">
                    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                        <button type="button" class="btn btn-secondary">1</button>
                        <button type="button" class="btn btn-secondary">2</button>

                        <div class="btn-group" role="group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                <a class="dropdown-item" href="#">Dropdown link</a>
                                <a class="dropdown-item" href="#">Dropdown link</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Button group
                    <small>vertical variation</small>
                </div>
                <div class="card-body">
                    <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
                        <button type="button" class="btn btn-secondary">Button</button>
                        <button type="button" class="btn btn-secondary">Button</button>
                        <button type="button" class="btn btn-secondary">Button</button>
                        <button type="button" class="btn btn-secondary">Button</button>
                        <button type="button" class="btn btn-secondary">Button</button>
                        <button type="button" class="btn btn-secondary">Button</button>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Button group
                    <small>vertical variation</small>
                </div>
                <div class="card-body">
                    <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
                        <button type="button" class="btn btn-secondary">Button</button>
                        <button type="button" class="btn btn-secondary">Button</button>
                        <div class="btn-group" role="group">
                            <button id="btnGroupVerticalDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop1">
                                <a class="dropdown-item" href="#">Dropdown link</a>
                                <a class="dropdown-item" href="#">Dropdown link</a>
                            </div>
                        </div>
                        <button type="button" class="btn btn-secondary">Button</button>
                        <button type="button" class="btn btn-secondary">Button</button>
                        <div class="btn-group" role="group">
                            <button id="btnGroupVerticalDrop2" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop2">
                                <a class="dropdown-item" href="#">Dropdown link</a>
                                <a class="dropdown-item" href="#">Dropdown link</a>
                            </div>
                        </div>
                        <div class="btn-group" role="group">
                            <button id="btnGroupVerticalDrop3" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop3">
                                <a class="dropdown-item" href="#">Dropdown link</a>
                                <a class="dropdown-item" href="#">Dropdown link</a>
                            </div>
                        </div>
                        <div class="btn-group" role="group">
                            <button id="btnGroupVerticalDrop4" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop4">
                                <a class="dropdown-item" href="#">Dropdown link</a>
                                <a class="dropdown-item" href="#">Dropdown link</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

mvc/Views/CoreUI/Theme/colors.cshtml
@{
    ViewData["Name"] = "Colors";
}
<div class="animated fadeIn">
    <div class="card">
        <div class="card-header">
            <i class="icon-drop"></i> Theme colors
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-primary">Primary</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-secondary">Secondary</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-success">Success</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-danger">Danger</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-warning">Warning</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-info">Info</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-light">Light</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-dark">Dark</div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <i class="icon-drop"></i> Grays
        </div>
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-md-4">
                    <div class="p-3 bg-gray-100">100</div>
                    <div class="p-3 bg-gray-200">200</div>
                    <div class="p-3 bg-gray-300">300</div>
                    <div class="p-3 bg-gray-400">400</div>
                    <div class="p-3 bg-gray-500">500</div>
                    <div class="p-3 bg-gray-600">600</div>
                    <div class="p-3 bg-gray-700">700</div>
                    <div class="p-3 bg-gray-800">800</div>
                    <div class="p-3 bg-gray-900">900</div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <i class="icon-drop"></i> Additional colors
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-blue">Blue</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-indigo">Indigo</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-purple">Purple</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-pink">Pink</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-red">Red</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-orange">Orange</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-yellow">Yellow</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-green">Green</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-teal">Teal</div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 mb-3 bg-cyan">Cyan</div>
                </div>
            </div>
        </div>
    </div>
</div>

mvc/Views/CoreUI/blank.cshtml
@{
    ViewData["Name"] = "Blank";
}
<div class="animated fadeIn">

</div>

mvc/Views/Shared/_AppHeader.cshtml
<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" asp-controller="CoreUI" asp-action="Index"></a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- remove:seed -->
    <ul class="nav navbar-nav d-md-down-none">
        <li class="nav-item px-3">
            <a class="nav-link" asp-controller="CoreUI" asp-action="Index">Dashboard</a>
        </li>
        <li class="nav-item px-3">
            <a class="nav-link" href="#">Users</a>
        </li>
        <li class="nav-item px-3">
            <a class="nav-link" href="#">Settings</a>
        </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
        @Html.Partial("_UserNav")
    </ul>
    <button class="navbar-toggler aside-menu-toggler" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- /remove:seed -->
</header>

mvc/Views/Shared/_Footer.cshtml
<footer class="app-footer">
    <span><a href="http://coreui.io">CoreUI</a> © 2018 creativeLabs.</span>
    <span class="ml-auto">Powered by <a href="http://coreui.io">CoreUI</a></span>
</footer>

mvc/Views/Shared/_SidebarNav.cshtml
<nav class="sidebar-nav">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" asp-controller="CoreUI" asp-action="Index" asp-route-id=""><i class="icon-speedometer"></i> Dashboard <span class="badge badge-primary">NEW</span></a>
        </li>
        <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-puzzle"></i>Theme</a>
            <ul class="nav-dropdown-items">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Theme" asp-route-id="colors"><i class="icon-drop"></i> Colors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Theme" asp-route-id="typography"><i class="icon-pencil"></i> Typography</a>
                </li>
            </ul>
        </li>
        <li class="nav-title">
            Components
        </li>
        <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-puzzle"></i> Base</a>
            <ul class="nav-dropdown-items">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="breadcrumb"><i class="icon-puzzle"></i> Breadcrumb</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="cards"><i class="icon-puzzle"></i> Cards</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="carousel"><i class="icon-puzzle"></i> Carousel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="collapse"><i class="icon-puzzle"></i> Collapse</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="forms"><i class="icon-puzzle"></i> Forms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="jumbotron"><i class="icon-puzzle"></i> Jumbotron</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="list-group"><i class="icon-puzzle"></i> List group</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="navs"><i class="icon-puzzle"></i> Navs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="pagination"><i class="icon-puzzle"></i> Pagination</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="popovers"><i class="icon-puzzle"></i> Popovers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="progress"><i class="icon-puzzle"></i> Progress</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="switches"><i class="icon-puzzle"></i> Switches</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="tables"><i class="icon-puzzle"></i> Tables</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="tabs"><i class="icon-puzzle"></i> Tabs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Components" asp-route-id="tooltips"><i class="icon-puzzle"></i> Tooltips</a>
                </li>
            </ul>
        </li>
        <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-cursor"></i> Buttons</a>
            <ul class="nav-dropdown-items">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Buttons" asp-route-id="buttons"><i class="icon-cursor"></i> Buttons</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Buttons" asp-route-id="button-group"><i class="icon-cursor"></i> Buttons Group</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Buttons" asp-route-id="dropdowns"><i class="icon-cursor"></i> Dropdowns</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Buttons" asp-route-id="social-buttons"><i class="icon-cursor"></i> Social Buttons</a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="CoreUI" asp-action="Charts" asp-route-id=""><i class="icon-pie-chart"></i> Charts</a>
        </li>
        <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-star"></i> Icons</a>
            <ul class="nav-dropdown-items">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Icons" asp-route-id="flags"><i class="icon-star"></i> Flags <span class="badge badge-success">NEW</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Icons" asp-route-id="font-awesome"><i class="icon-star"></i> Font Awesome <span class="badge badge-secondary">4.7</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Icons" asp-route-id="simple-line-icons"><i class="icon-star"></i> Simple Line Icons</a>
                </li>
            </ul>
        </li>
        <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-bell"></i> Notifications</a>
            <ul class="nav-dropdown-items">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Notifications" asp-route-id="alerts"><i class="icon-bell"></i> Alerts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Notifications" asp-route-id="badge"><i class="icon-bell"></i> Badge</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="CoreUI" asp-action="Notifications" asp-route-id="modals"><i class="icon-bell"></i> Modals</a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="CoreUI" asp-action="Widgets" asp-route-id=""><i class="icon-calculator"></i> Widgets <span class="badge badge-primary">NEW</span></a>
        </li>
        <li class="divider"></li>
        <li class="nav-title">
            Extras
        </li>
        <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-star"></i>Pages</a>
            <ul class="nav-dropdown-items">
                <li class="nav-item">
                    <a class="nav-link" asp-area="Pages" asp-controller="" asp-action="Login" asp-route-id=""><i class="icon-star"></i> Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Pages" asp-controller="" asp-action="Register" asp-route-id=""><i class="icon-star"></i> Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Pages" asp-controller="" asp-action="_404" asp-route-id=""><i class="icon-star"></i> Error 404</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Pages" asp-controller="" asp-action="_500" asp-route-id=""><i class="icon-star"></i> Error 500</a>
                </li>
            </ul>
        </li>
        <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-puzzle"></i>Home</a>
            <ul class="nav-dropdown-items">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index" asp-route-view=""><i class="fa fa-windows"></i>Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="About" asp-route-view=""><i class="icon-speech"></i>About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Contact" asp-route-view=""><i class="icon-envelope"></i>Contact</a>
                </li>
            </ul>
        </li>
        <li class="nav-item mt-auto">
            <a class="nav-link nav-link-success" href="http://coreui.io" target="_top"><i class="icon-cloud-download"></i> Download CoreUI</a>
        </li>
        <li class="nav-item">
            <a class="nav-link nav-link-danger" href="http://coreui.io/pro/" target="_top"><i class="icon-layers"></i> Try CoreUI <strong>PRO</strong></a>
        </li>
    </ul>
</nav>